# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'CashDash' do
	pod 'Parse'
	pod 'ParseUI'
	pod 'ParseFacebookUtilsV4'
	pod 'SwiftyJSON'
	pod 'Alamofire'
	pod 'Firebase'
end
