# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'CashDash' do
	pod 'Parse', '~> 1.13.0'
	pod 'ParseUI'
	pod 'ParseFacebookUtilsV4'
	pod 'ParseFacebookUtils'
	pod 'ParseTwitterUtils'
	pod 'SwiftyJSON'
	pod 'Alamofire'
end
